/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Symphony.WebApp;

import org.junit.Test;

import com.automation.framework.BrowserStrategy;
import com.automation.symphony.ResetPasswordObject;
import com.automation.symphony.SignInObject;

import org.openqa.selenium.WebDriver;

import static org.junit.Assert.*;

import org.junit.After;
import org.junit.Before;

public class SignInPageTests {
	public BrowserStrategy browser;
	public SignInObject signInPage;
	public ResetPasswordObject resetPasswordPage;
	public WebDriver webdriver;
	
	@Before
	public void preconditions() throws Exception {
		browser = new BrowserStrategy(System.getProperty("browser"));
		webdriver = browser.getDriver();
    	signInPage = new SignInObject(webdriver);
    	resetPasswordPage = new ResetPasswordObject(webdriver);
	}
	
    @Test 
    public void Should_OpenPasswordPageWithRecoverPasswordButton_When_ClickingPasswordLink() throws Exception {
    	signInPage.open();
    	signInPage.clickForgotYourPasswordLink();
    	assertTrue(resetPasswordPage.getRecoverPassword().isDisplayed());
    }
    
    @Test 
    public void Should_DisplayErrorMessage_When_LoginWithoutParameters() throws Exception {
    	signInPage.open();
    	signInPage.clickSignInToAccountButton();
    	assertEquals(signInPage.getErrorMessage(), "All fields are required.");
    }
    
    @Test 
    public void Should_DisplayFrenchMessage_When_SelectingLanguageAsFrench() throws Exception {
    	signInPage.open();
    	signInPage.selectLanguage("french");
    	assertEquals(signInPage.languageLabelContent(), "Choix de la langue");
    }
    
    @Test 
    public void Should_DisplayJapaneseMessage_When_SelectingLanguageAsJapanese() throws Exception {
    	signInPage.open();
    	signInPage.selectLanguage("japanese");
    	assertEquals(signInPage.languageLabelContent(), "言語の設定");
    }
    
    @Test 
    public void Should_DisplayEnglishMessage_When_SelectingLanguageAsEnglishAfterItWasFrench() throws Exception {
    	signInPage.open();
    	signInPage.selectLanguage("french");
    	signInPage.selectLanguage("english");
    	assertEquals(signInPage.languageLabelContent(), "Language Preference");
    }
    
    @After
    public void cleanUp() {
    	webdriver.close();
    }
    
}
